/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SlaRouteImport } from './routes/sla'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardLicenseRouteImport } from './routes/dashboard/license'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardApiKeysRouteImport } from './routes/dashboard/api-keys'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as AuthDeviceRouteImport } from './routes/auth/device'
import { Route as ApiOgRouteImport } from './routes/api/og'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SlaRoute = SlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLicenseRoute = DashboardLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardApiKeysRoute = DashboardApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthDeviceRoute = AuthDeviceRouteImport.update({
  id: '/auth/device',
  path: '/auth/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/downloads': typeof DownloadsRoute
  '/dpa': typeof DpaRoute
  '/faq': typeof FaqRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sla': typeof SlaRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/api/og': typeof ApiOgRoute
  '/auth/device': typeof AuthDeviceRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/license': typeof DashboardLicenseRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/downloads': typeof DownloadsRoute
  '/dpa': typeof DpaRoute
  '/faq': typeof FaqRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sla': typeof SlaRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/api/og': typeof ApiOgRoute
  '/auth/device': typeof AuthDeviceRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/license': typeof DashboardLicenseRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/downloads': typeof DownloadsRoute
  '/dpa': typeof DpaRoute
  '/faq': typeof FaqRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sla': typeof SlaRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/api/og': typeof ApiOgRoute
  '/auth/device': typeof AuthDeviceRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/license': typeof DashboardLicenseRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/cookies'
    | '/downloads'
    | '/dpa'
    | '/faq'
    | '/issues'
    | '/login'
    | '/privacy'
    | '/roadmap'
    | '/signup'
    | '/sitemap.xml'
    | '/sla'
    | '/support'
    | '/terms'
    | '/api/og'
    | '/auth/device'
    | '/dashboard/account'
    | '/dashboard/api-keys'
    | '/dashboard/billing'
    | '/dashboard/license'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/downloads'
    | '/dpa'
    | '/faq'
    | '/issues'
    | '/login'
    | '/privacy'
    | '/roadmap'
    | '/signup'
    | '/sitemap.xml'
    | '/sla'
    | '/support'
    | '/terms'
    | '/api/og'
    | '/auth/device'
    | '/dashboard/account'
    | '/dashboard/api-keys'
    | '/dashboard/billing'
    | '/dashboard/license'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/cookies'
    | '/downloads'
    | '/dpa'
    | '/faq'
    | '/issues'
    | '/login'
    | '/privacy'
    | '/roadmap'
    | '/signup'
    | '/sitemap.xml'
    | '/sla'
    | '/support'
    | '/terms'
    | '/api/og'
    | '/auth/device'
    | '/dashboard/account'
    | '/dashboard/api-keys'
    | '/dashboard/billing'
    | '/dashboard/license'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  DownloadsRoute: typeof DownloadsRoute
  DpaRoute: typeof DpaRoute
  FaqRoute: typeof FaqRoute
  IssuesRoute: typeof IssuesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RoadmapRoute: typeof RoadmapRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlaRoute: typeof SlaRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ApiOgRoute: typeof ApiOgRoute
  AuthDeviceRoute: typeof AuthDeviceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sla': {
      id: '/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof SlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/license': {
      id: '/dashboard/license'
      path: '/license'
      fullPath: '/dashboard/license'
      preLoaderRoute: typeof DashboardLicenseRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/api-keys': {
      id: '/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof DashboardApiKeysRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/device': {
      id: '/auth/device'
      path: '/auth/device'
      fullPath: '/auth/device'
      preLoaderRoute: typeof AuthDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardApiKeysRoute: typeof DashboardApiKeysRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardLicenseRoute: typeof DashboardLicenseRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardApiKeysRoute: DashboardApiKeysRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardLicenseRoute: DashboardLicenseRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  CookiesRoute: CookiesRoute,
  DownloadsRoute: DownloadsRoute,
  DpaRoute: DpaRoute,
  FaqRoute: FaqRoute,
  IssuesRoute: IssuesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RoadmapRoute: RoadmapRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlaRoute: SlaRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ApiOgRoute: ApiOgRoute,
  AuthDeviceRoute: AuthDeviceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
